### ISSUE TITLE
В мастере копирования сборки необходимо реализовать автоматическое именование

### ISSUE THREAD

**Issue by FokinaLG** [Fresh-Byte/ci#1]
Если выбрать среду "Репозиторий шаблонов", то имя сборки должно автоматически генерироваться в текущую дату и время в формате yyyy.mm.dd_hh.mm.ss

**Comment by Rombs** [comment]
Реализовано следующее поведение:
1. Для любой среды
2. Если поле "Название" пустое
3. Подставляется название последней папки в поле "Директория"
